package il.co.dcd.composermapper.parser; import il.co.dcd.composermapper.index.Indexes; import il.co.dcd.composermapper.model.*; import il.co.dcd.composermapper.util.XmlUtil; import org.w3c.dom.*; import java.nio.file.Path; import java.util.*;
public class FormatFileParser {
  public List<FormatDef> parse(Path xml, Indexes x){ List<FormatDef> out=new ArrayList<>(); walk(XmlUtil.parse(xml).getDocumentElement(), xml, x, out); return out; }
  private void walk(Element e, Path xml, Indexes x, List<FormatDef> out){ if("fmtDef".equals(e.getTagName())) out.add(parseFormat(e,xml,x)); for(Element c:XmlUtil.childElements(e)) walk(c,xml,x,out); }
  private FormatDef parseFormat(Element e, Path xml, Indexes x){ FormatDef f=new FormatDef(); f.setId(XmlUtil.attr(e,"id")); f.setSourceFile(xml); Element root=null; for(Element c:XmlUtil.childElements(e)){ root=c; break; } if(root!=null) f.setRootTag(toNode(root,f,x,"/"+nodeSegment(root))); return f; }
  private TagNode toNode(Element e, FormatDef f, Indexes x, String path){ TagNode n=new TagNode(e.getTagName()); for(int i=0;i<e.getAttributes().getLength();i++){ var a=e.getAttributes().item(i); n.getAttributes().put(a.getNodeName(),a.getNodeValue()); captureSerializationFlag(e,a,f,path); String lower=(a.getNodeName()+"="+a.getNodeValue()).toLowerCase(); if(lower.contains("table")||lower.contains("column")||lower.contains("sql")||lower.contains("jdbc")) f.getInferredExternalDependencies().add("Database"); if(lower.contains("url")||lower.contains("endpoint")||lower.contains("service")||lower.contains("soap")||lower.contains("http")) f.getInferredExternalDependencies().add("API/Service"); }
    captureDatabaseLookup(e,n,f);
    f.getReferencedXmlTags().add(e.getTagName()); String mapped=x.tagToClass().get(e.getTagName()); if(mapped!=null) f.getReferencedMappedJavaClasses().add(mapped); for(Element c:XmlUtil.childElements(e)) n.getChildren().add(toNode(c,f,x,path+"/"+nodeSegment(c))); return n; }
  private void captureSerializationFlag(Element e, Node a, FormatDef f, String path){ String attrName=a.getNodeName(); if(!"transparent".equals(attrName)&&!"unnamed".equals(attrName)) return; String dataName=e.getAttribute("dataName"); String nodeIdentifier=(dataName!=null&&!dataName.isBlank())?dataName:"path="+path; f.getSerializationFlags().add(nodeIdentifier+" "+attrName+"="+a.getNodeValue()); }
  private String nodeSegment(Element e){ return e.getTagName()+"["+siblingPosition(e)+"]"; }
  private int siblingPosition(Element e){ int position=1; for(Node n=e.getPreviousSibling();n!=null;n=n.getPreviousSibling()) if(n instanceof Element previous && previous.getTagName().equals(e.getTagName())) position++; return position; }
  private void captureDatabaseLookup(Element e, TagNode n, FormatDef f){ String fromTable=n.getAttributes().get("fromTable"); String fromColumn=n.getAttributes().get("fromColumn"); String keyValue=n.getAttributes().get("keyValue"); if(fromTable!=null||fromColumn!=null||keyValue!=null){ f.getInferredExternalDependencies().add("Database"); f.getDatabaseLookups().add(new FormatDef.DatabaseLookup(e.getTagName(),fromTable,fromColumn,keyValue)); } }
}
