# Central Composer tag-to-class mappings.
XML=demo.bankcomposer.tags.XMLDocument
CCDSEServerOperation=demo.bankcomposer.tags.CCDSEServerOperation
opStep=demo.bankcomposer.tags.OpStep
refFormat=demo.bankcomposer.tags.RefFormat
fmtDef=demo.bankcomposer.tags.FormatDefinition
context=demo.bankcomposer.tags.ContextDefinition
CCXML=demo.bankcomposer.formats.CCXML
CCString=demo.bankcomposer.formats.CCString
CCDate=demo.bankcomposer.formats.CCDate
CCBoolean=demo.bankcomposer.formats.CCBoolean
CCTcoll=demo.bankcomposer.formats.CCTcoll
CCTableFormat=demo.bankcomposer.formats.CCTableFormat
NumberFormat=demo.bankcomposer.formats.NumberFormat
nilDecorator=demo.bankcomposer.formats.NilDecorator

